name: Cypress E2E Test Run

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      target_env:
        description: "Select environment to test"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: uhg-runner

    strategy:
      matrix:
        ENV_NAME: [dev, test]

    steps:
      - name: Skip non-selected environment (manual trigger only)
        if: github.event_name == 'workflow_dispatch' && matrix.ENV_NAME != github.event.inputs.target_env
        run: echo "Skipping environment ${{ matrix.ENV_NAME }} because target_env is ${{ github.event.inputs.target_env }}."
        shell: bash

      - name: Cleanup
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Installing Cypress Dependencies and xvfb
        if: runner.os == 'Linux'
        run: |
          wget https://repo1.uhc.com/artifactory/security-ubuntu-cache/ubuntu/pool/main/x/xorg-server/xserver-common_21.1.4-2ubuntu1.7~22.04.9_all.deb -O /tmp/xserver-common.deb
          wget https://repo1.uhc.com/artifactory/security-ubuntu-cache/ubuntu/pool/universe/x/xorg-server/xvfb_21.1.3-2ubuntu2.9_amd64.deb -O /tmp/xvfb.deb
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth /tmp/xserver-common.deb /tmp/xvfb.deb
          rm /tmp/xserver-common.deb /tmp/xvfb.deb

      - name: npm Install
        run: |
          npm config set registry https://repo1.uhc.com/artifactory/api/npm/npm-virtual/
          npm install

      - name: Set Environment Variables for ${{ matrix.ENV_NAME }}
        run: |
          if [ "${{ matrix.ENV_NAME }}" = "dev" ]; then
            echo "BASE_URL=${{ secrets.DEV_BASE_URL }}" >> $GITHUB_ENV
            echo "USERNAME=${{ secrets.DEV_USERNAME }}" >> $GITHUB_ENV
            echo "PASSWORD=${{ secrets.DEV_PASSWORD }}" >> $GITHUB_ENV
          elif [ "${{ matrix.ENV_NAME }}" = "test" ]; then
            echo "BASE_URL=${{ secrets.TEST_BASE_URL }}" >> $GITHUB_ENV
            echo "USERNAME=${{ secrets.TEST_USERNAME }}" >> $GITHUB_ENV
            echo "PASSWORD=${{ secrets.TEST_PASSWORD }}" >> $GITHUB_ENV
          fi

      - name: Run Cypress Tests on ${{ matrix.ENV_NAME }}
        run: |
          npx cypress run --env BASE_URL=$BASE_URL,USERNAME=$USERNAME,PASSWORD=$PASSWORD

      - name: Final Summary
        run: echo "✅ Cypress Tests Completed Successfully on ${{ matrix.ENV_NAME }}"

      - name: Upload Cypress Artifacts (Screenshots, Videos, Reports)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-artifacts-${{ matrix.ENV_NAME }}
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos

      - name: Print Report URL
        run: |
          echo "Report URL for ${{ matrix.ENV_NAME }}: https://s3api-dmz.optum.com/orx-cat-ar/index.html"
